### ISSUE TITLE
Graph in Security Detail window issue. 

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#110]
See screen shot example, the + on the graph looks wrongly positioned even though the date when hovering looks correct. + should be on start of graph line. 
The issue only seems to exist with recently purchased securities with a smallish number of entries in the Security history window.
Sean response on Slack.
“ I think the issue is probably that the dates are spaced far enough apart in that graph that it is positioned at 07.11.2023 0:00:00 and maybe 07.11.2023 12:00:00 would line up better with the tick marks”.
![Security Detail Graph](https://github.com/TheInfiniteKind/moneydance_open/assets/59656614/190f49da-9d7c-4205-9aac-20e23c06365f)

**Comment by yogi1967** [comment]
@Derekkent23 - is this still an issue?

**Comment by Derekkent23** [comment]
Retested issue is fixed
