### ISSUE TITLE
Bug: Foresight (Desktop Widget) prior settings lost between data sets

### ISSUE THREAD

**Issue by Kevin-N749** [TheInfiniteKind/moneydance_open#115]
Moneydance 2023.3 (5064)

To recreate:  
Open Moneydance.
Open the Foresight (Desktop widget) settings.  
Select the desired account(s) for the Foresight (Desktop widget)
Switch to a different data set with a different account structure OR create a new data set.
Switch back to the original data set, the Foresight (Desktop Widget) does not remember its prior account selections for that data set.
In the settings display, the Foresight (Desktop Widget) displays ALL account in both the 'Available' AND the 'Selected' columns.

**Comment by Kevin-N749** [comment]
Workaround: 
Quit Moneydance using File > Quit then open the desired _data set x_ instead of using File > Open > _data set x_

**Comment by yogi1967** [comment]
FYI. This should be in the latest Alpha MD2024(5101)
