### ISSUE TITLE
Foresight Forecast Summary Page widget does not appear to remember settings across an MD restart

### ISSUE THREAD

**Issue by kodacapo** [TheInfiniteKind/moneydance_open#117]
Marked closed before, but still a problem in Build 5064

**Comment by sreilly** [comment]
@kodacapo are there any specifics you can share about what settings aren't remembered? Or is it that they aren't remembered under certain circumstances?

**Comment by kodacapo** [comment]
Sean, here’s the scenario I have encountered (and repeated several times with the same result):

1. Open MD with account file A. Foresight widget slowly draws 3 months worth of transactions over all (30+) accounts.
2. Adjust Foresight parameters to just draw 2 weeks worth for 2 accounts.
3. Switch to some account.
4. Switch back to Summary page. Foresight behaves correctly.
5. Quit MD.
6. Open MD (opens with account file A).
7. Summary page is normal, Foresight behaves as specified in step 2.
8. File/Open account file B.
9. Summary page shows 3 months of transactions over all 5 accounts.
10. Adjust Foresight parameters to just draw 2 weeks worth for 4 accounts.
11. Quit MD.
12. Open MD (opens with account file B).
13. Summary page is normal, Foresight behaves as specified in step 10.
14. File/Open account file A.
15. Foresight widget slowly draws 3 months worth of transactions over all (30+) accounts.

I hope this helps!

Thanks,

- - -   /-/ a n s


On Jan 26, 2024, at 04:13, Sean Reilly ***@***.***> wrote:



@kodacapo<https://urldefense.com/v3/__https://github.com/kodacapo__;!!CGUSO5OYRnA7CQ!aKIeLIgxhXBbJ9wqHcxI9WEeDydaxMFPRkgEh9duUm7cXbNPBAvTo-XL8PQhTKXyPUsKCieM4HpIiBs3d2u0KJ2TIoUvdw$> are there any specifics you can share about what settings aren't remembered? Or is it that they aren't remembered under certain circumstances?

**Comment by yogi1967** [comment]
Also, refer here:
https://infinitekind.tenderapp.com/discussions/problems/96894-money-foresight-forecasting-not-remembering-settings

**Comment by Kevin-N749** [comment]
Also refer here:
https://github.com/TheInfiniteKind/moneydance_open/issues/115

**Comment by Robbie8** [comment]
I am receiving the same issue on Moneydance version 5064. It occurs after moving from one open file to another without quitting Moneydance in-between.
Moneydance ticket - https://infinitekind.tenderapp.com/discussions/problems/96894-money-foresight-forecasting-not-remembering-settings

**Comment by sreilly** [comment]
This is now fixed and I'm working on getting a preview available in the next few days. Sorry about the bug!

**Comment by yogi1967** [comment]
FYI. This should be in the latest Alpha MD2024(5101)
