### ISSUE TITLE
Question:  Are any plugin methods invoked by non-primary threads?

### ISSUE THREAD

**Issue by M-Pixel** [TheInfiniteKind/moneydance_open#12]
I noticed that `synchronized` is used [in some of the plugins](https://github.com/TheInfiniteKind/moneydance_open/blob/cb16247d6ead3262493f892dea8663bf9096c70c/src/com/moneydance/modules/features/txtimport/Main.java#L106).  I'm wondering if this is unnecessary and to be ignored, or if users of this kit need to assume that `invoke` (and possibly other methods) might be called by the application from multiple threads.

**Comment by sreilly** [comment]
The extensions may be initialised off of the swing main thread, for example upon application launch which could in theory happen before the UI is loaded.  I can't think of a time when one of methods such as invoke might be called off the main swing thread, but in theory it is possible.  Extensions can also register themselves as listeners to various data model objects and those can definitely be called off the main thread, for example when objects are updated from the sync layer.

**Comment by yogi1967** [comment]
M-Pixel. I wrote this readme for Python, but a lot of it will apply to Java. Take a look at the bits regarding the Swing Event Dispatch Thread (EDT) etc...
[readme.txt](https://github.com/TheInfiniteKind/moneydance_open/files/6269960/readme.txt)
