### ISSUE TITLE
Duplicate a transaction

### ISSUE THREAD

**Issue by lordpixel23** [TheInfiniteKind/moneydance_open#120]
Every week I pay my kid allowance. I just was a few weeks behind so I had to enter the same transaction 10 times.

What I wanted at that moment: 

1. Press Control (or Command) D
2. Current transaction is duplicated, all fields, Description, Memo, Category, Amount
3. Focus is put in the Date field so I can type a new Date, hit return

**Comment by yogi1967** [comment]
Andrew. FYI - This is the wrong place for IK support. You should repost on the proper forum:

https://infinitekind.tenderapp.com/discussions


Regardless. Right click. Duplicate transaction.

**Comment by lordpixel23** [comment]
Apologies. I looked for this 3 times yesterday before I posted this and didn't see it. 

If you were to add it to the main menubar (e.g. in File or Edit) then I would have found it because one can search the menubar on Mac OS (and some individual Windows apps.). I'd all so assign it Ctrl-D. 

Anyway, I'll close this, sorry for the noise.

**Comment by sreilly** [comment]
Adding this to the main menu is a great idea though.  It should be possible to do, but I probably won't add everything from the register's context menu since that might get a bit too cluttered.
