### ISSUE TITLE
The blank category in Moneydance seems to be stuck in GBP

### ISSUE THREAD

**Issue by lordpixel23** [TheInfiniteKind/moneydance_open#126]
Not sure if everyone's Moneydance does this or just mine. For me, new Transactions are created with a “blank” category by default. For some reason, mine is stuck in GBP, I cannot edit that currency, but, most of my accounts are USD.

<img width="383" alt="image" src="https://github.com/user-attachments/assets/38cb2a60-6ff9-4e0d-a5d6-613f7c215397">

The consequence of this is if I have a run of Unconfirmed transactions where they have all been assigned to the blank category, I get all this visual noise of having all the USD amounts translated into GBP with all the exchange rates. It makes it very hard to see what is going on until all the Categories are set.

<img width="268" alt="image" src="https://github.com/user-attachments/assets/9d0a9116-0611-4c5e-acaa-244e8a0289ea">

Is it just me... can I fix this GBP thing somehow or is this a Moneydance bug?

**Comment by yogi1967** [comment]
Andrew. This is the wrong place for IK support. You should repost on the proper forum:

https://infinitekind.tenderapp.com/discussions

However, once a category has been created, then the currency is fixed. You probably need to change the default category to one that's setup in USD.

**Comment by lordpixel23** [comment]
Thanks. I wonder how it happened in the first place. Nevertheless, it'll work. Closing.
