### ISSUE TITLE
Dropbox Folder sync folder isn't initialised upon setup

### ISSUE THREAD

**Issue by sreilly** [TheInfiniteKind/moneydance_open#14]
When setting up the first data set to sync with the "Dropbox Folder" method, the <dropbox>/.moneydancesync folder isn't created if it doesn't already exist.

From Derek Kent's original report:

> Set up as a new user, no “.moneydancesync” folder in Dropbox. When I set a sync password and selected Dropbox Folder clicking OK does not work. The process would not move forward to the next screen. No “.moneydancesync” folder created.

[internal issue](https://github.com/TheInfiniteKind/moneydance_desktop/issues/5506)

**Comment by sreilly** [comment]
Fixed in build 3065

**Comment by Derekkent23** [comment]
Build 3065, confirm for new users the folder “.moneydancesync” is created in Dropbox when using the sync method Dropbox Folder.
