### ISSUE TITLE
macOS 11 (big sur) system setting to open document windows in tabs breaks MD windows

### ISSUE THREAD

**Issue by sreilly** [TheInfiniteKind/moneydance_open#16]
If the system settings in macOS 11 are set to open document windows in tabs instead of new windows, then nearly all Moneydance windows (all "frames") will open in tabs which isn't right. The requirement to ask customers to change their tab preferences to “Never” or “In full Screen” on macOS Big Sur should be fixed.

Reported by @dwg1957

**Comment by sreilly** [comment]
I've fixed this in the macOS launcher that loads the JVM and then starts the java part of moneydance. In case you're interested, that is also open source and available [here](https://github.com/TheInfiniteKind/appbundler).

**Comment by yogi1967** [comment]
Does this fix ([[NSUserDefaults standardUserDefaults] setValue:@"manual" forKey:@"AppleWindowTabbingMode"]) set the setting just for this app launch..? Or is it changing the setting permanently for the user on all their apps..? Is there a way I can set this in my Moneydance launch script using a -D setting?

**Comment by yogi1967** [comment]
actually, don't worry. I will just use:
`defaults write -g AppleWindowTabbingMode -string manual`

**Comment by yogi1967** [comment]
PS - Nice fix!
