### ISSUE TITLE
Memorized Income & Expense Report Title Skewed to the Right

### ISSUE THREAD

**Issue by NickWard999** [TheInfiniteKind/moneydance_open#23]
Dell XPS / Windows 10 Home 20H2 / MD 3064

This has been happening for multiple build cycles.

When I print a memorized Income & Expense Report, in either Landscape or portrait the report title is skewed to the right and cut off the page. I have attached a PDF of the report in both layouts, and a screen shot of the report in MD.

[md_print_title.pdf](https://github.com/TheInfiniteKind/moneydance_open/files/6273226/md_print_title.pdf)
![image](https://user-images.githubusercontent.com/59615855/113903957-c3240500-978e-11eb-9c2e-54a02db068f0.png)

**Comment by yogi1967** [comment]
Hmm. Works perfectly for me.. Mac and build 3064

**Comment by sreilly** [comment]
It was broken but was only apparent when the column widths were less than the page width. It's now fixed for the next preview (3065)
