### ISSUE TITLE
Auto Commit Transaction Reminders vs Manual Enter Transaction Reminders with splits

### ISSUE THREAD

**Issue by NickWard999** [TheInfiniteKind/moneydance_open#24]
Dell XPS, Window 10 20H2, MD 3064 and previous versions, long standing bug.

I have a Transaction Reminder, specifically my mortgage, where I do not use the escrow account. 

Loan Setup
![image](https://user-images.githubusercontent.com/59615855/113940375-938af200-97ba-11eb-9fdc-d3e1fe124881.png)

Reminder Setup
![image](https://user-images.githubusercontent.com/59615855/113940575-e49ae600-97ba-11eb-9289-da066e550796.png)

When the auto commit code records the transaction, the transaction is inserted with three splits, 1 for the mortgage loan, one for the mortgage interest, and one for Select Categories. 
![image](https://user-images.githubusercontent.com/59615855/113941199-e74a0b00-97bb-11eb-923d-9cb562d86ea2.png)
![image](https://user-images.githubusercontent.com/59615855/113941242-f630bd80-97bb-11eb-8403-aad05a0983e2.png)

When I manually Record the Transaction from the Reminders notification, the transaction is recorded with two splits one for the Mortgage Loan and one for the Mortgage Interest. 
![image](https://user-images.githubusercontent.com/59615855/113941322-1c565d80-97bc-11eb-8c96-193e4afe6f1a.png)
![image](https://user-images.githubusercontent.com/59615855/113941346-2aa47980-97bc-11eb-8dd8-1dae9d9b016d.png)
![image](https://user-images.githubusercontent.com/59615855/113941370-35f7a500-97bc-11eb-8715-069370786b68.png)

Early in the year Feb 2021 - Stuart Beasley and I looked into this a little further
"This is a bug.. If you use auto-commit and let MD create the reminder when you restart then you get a zero split created for the escrow. If you manually auto-commit then you only get 2 splits and the escrow is ignored.
the errant code is in module/method:
com.infinitekind.moneydance.model.LoanFields.saveToTransaction(ParentTxn)
it checks for no escrow and loads a default account. Then later it checks for a null escrow account and if it’s set, and there is no 3rd split, then it adds a zero split. This check is thus not working due to the default escrow account being loaded earlier on..
Whereas using the record next occurrence option from the reminder calendar calls a different bit of code within the LoanTxnReminderNotificationWindow class which calls com.moneydance.apps.md.view.gui.LoanReminderTxnEditPanel.saveTransaction(ParentTxn) . This checks for zero escrow value and if so then it explicitly removes the split...
So, oddly, the code for committing reminders is different...."

**Comment by sreilly** [comment]
Thanks for the excellent detail!  I've fixed this for the next preview - build 3065

**Comment by yogi1967** [comment]
😉 😃 ✅

**Comment by NickWard999** [comment]
Thanks

Nick Ward
+1 780-394-0561
