### ISSUE TITLE
Build 3064 - Keep seeing these messages in console... (com.moneydance.apps.md.view.gui.txnreg.CategorySuggestionsPanel)?

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#25]
Why are these messages being generated?

adding actions panel
No appearance for: javax.swing.JPanel should ensure appearance?
No appearance for: com.moneydance.apps.md.view.gui.txnreg.CategorySuggestionsPanel should ensure appearance?
No appearance for: javax.swing.JScrollPane should ensure appearance?
No appearance for: javax.swing.JList should ensure appearance?

from com.moneydance.apps.md.view.gui.txnreg.CategorySuggestionsPanel()?

**Comment by sreilly** [comment]
These are coming from vaqua. They are annoying, but not yet worth prioritising.
