### ISSUE TITLE
Build 3064 - Mac (VAQua). Unsigned extensions warning banner is now yellow on transparent instead of RED 

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#27]
Mac. The unsigned extension warning banner on the home page is unreadable. Basically the RED background has gone and just the yellow remains… See screenshots from 3036 and 3064
<img width="1411" alt="3051" src="https://user-images.githubusercontent.com/22958485/114070265-ba6b2600-9897-11eb-9e8e-ce887ebad4cc.png">
<img width="1425" alt="3036" src="https://user-images.githubusercontent.com/22958485/114070269-bb9c5300-9897-11eb-9fa6-085a6ec43ecd.png">

**Comment by sreilly** [comment]
Fixed as of 3066
