### ISSUE TITLE
Build 3064 - Dark mode dropdown arrow, not clearly visible

### ISSUE THREAD

**Issue by NickWard999** [TheInfiniteKind/moneydance_open#28]
The dropdown / combobox arrow heads in Dark Mode are almost invisible against the dark background.. Such as the Payments per year field or Number of payments. A  contrasting colour, would be much better.

![image](https://user-images.githubusercontent.com/59615855/114080071-2afa4e80-9868-11eb-95b9-b23324e47b68.png)

also in the Transaction Reminder screen

![image](https://user-images.githubusercontent.com/59615855/114080418-9f34f200-9868-11eb-9c01-e9b21a8f74e7.png)

**Comment by sreilly** [comment]
This should be fixed now with the new/different Flat Dark theme
