### ISSUE TITLE
Windows 10. Some dialog window looks visibly crude  on later preview builds.

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#30]
I think these users have a justifiable comment which I agree with
https://infinitekind.tenderapp.com/discussions/problems/69352-ui-display-on-windows-10-since-latest-preview-build

**Comment by dwg1957** [comment]
In my view it is not a clean, professional look, the heavy borders I think also make it difficult to read.

I did not think the previous look was "broken" and I do not see this as an improvement.

**Comment by sreilly** [comment]
The previous look wasn't broken, but when in dark mode the custom colours weren't being applied to menu backgrounds, making them unreadable which was a bigger deal-breaker than them looking ugly. A better fix is in progress.

**Comment by dwg1957** [comment]
Thanks for the clarification Sean, dark mode has proven to be problematic over the versions, I've never been a user of the mode myself - well not since the days of DOS and dumb terminals and tend to find the while background and dark text easier to read.

**Comment by Derekkent23** [comment]
Thanks Sean for the acknowledgement of the issue and confirmation that a fix is underway.

**Comment by Derekkent23** [comment]
With build 6066 windows look visibly more polished, with the exception as outline in new issue #38
