### ISSUE TITLE
Summary page Stock Price list and Reports showing Prices

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#31]
Summary page Stock Price list only displays up to two decimal places. Change this to show the true value as in the Current Price for the Security in its associated Security History window. This is especially relevant when the price is less than one and quoted to four decimal places. Also in reports such a NET WORTH the price should be displayed in full, not limited to two decimal places. The benefits of the Stock Price List is degraded in these cases and mean opening the Security History window for each to get a true picture of its current price.

**Comment by sreilly** [comment]
This is fixed on the summary page in 3066.  If this is also a problem in a report can you let me know which report it is?

**Comment by sreilly** [comment]
If it is a problem in a report, please file a separate issue for the report

**Comment by Derekkent23** [comment]
Great. Will open another issue related to reports.
