### ISSUE TITLE
Print Font Size.

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#32]
When the APPEARANCE tab was added the PRINTING, tab was removed. In the PRINTING tab you could not only select the Font but the Font Size. In the APPEARANCE tab you can set the Font, but not its size. Please add back the ability to set printing Font Size.

**Comment by sreilly** [comment]
re-added in build 3068

**Comment by yogi1967** [comment]
Confirmed. It's now back |-)
