### ISSUE TITLE
Build 3065 is using AdoptOpenJDK 15.0.1 and support for 15.0.2 ended March 2021

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#33]
(as flagged by dwg). Should 2021.1 (stable) at the very least use the terminal release of 15.0.2+7? But support for this ends March 2021. What is the Java version strategy for 2021.2 given 16 is out and 17 is planned?

**Comment by sreilly** [comment]
There are still some problems with moving to 16 right now, but we'll aim to release 2021 with 15... hopefully 15.0.2. For now I'm closing this because even the current 15 is stable for our purposes.
