### ISSUE TITLE
Show more decimal places for securities in reports

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#34]
Reports, Net Worth and Portfolio only displays up to two decimal places for Security prices. Change this to show the true value as in the Current Price for the Security in its associated Security History window. This is especially relevant when the price is less than one and quoted to four decimal places. The benefits of the reports are degraded in these cases and means opening the Security History window for each to get a true picture of its current price.

**Comment by sreilly** [comment]
Reports to update:
- [ ] Net Worth
- [ ] Portfolio

**Comment by Derekkent23** [comment]
Build 4072 has fixed this issue
