### ISSUE TITLE
Build 3065 on Mac Networth Graph Date popup range selector not working properly (Suspect VAQua issue)

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#37]
On first attempt you can see all the date rate options. On second attempt, the popup window stops at Last Week. If you click out, and reset, then. they all appear. Then again, they are gone. If you click cmd-D when they are gone and click away, then the date range selector doesn't work at all.

Windows is fine.

Mac build 3034 is fine.

Suspect VAQua issue.

Screen shots show before and after reset with missing options

<img width="1473" alt="Screenshot 2021-04-21 at 18 50 08" src="https://user-images.githubusercontent.com/22958485/115599505-9cf47e00-a2d3-11eb-939f-4d08fc93439f.png">
<img width="1459" alt="Screenshot 2021-04-21 at 18 50 00" src="https://user-images.githubusercontent.com/22958485/115599508-9e25ab00-a2d3-11eb-9d4c-4559630bb9be.png">

**Comment by sreilly** [comment]
This was a weird one, but it's now fixed for build 3069
