### ISSUE TITLE
Many Graphs and Reports under Edit have truncated text.

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#38]
Most windows affected by issue #30 have been fixed in build 3066. However as tested on Windows 10 on some computers one remains. Many Graphs and Reports under Edit use the line:
Select:   All   None   Type   Except Type   Show:   By Individual 
This is still truncated and parts are unreadable, see screen shot.
Note: on Linux Feren OS the line looks OK.
![Menu - Select  All None Type  Except Type  Show  By Individual](https://user-images.githubusercontent.com/59656614/115984601-e11ba300-a59f-11eb-9faf-ec7cb68e16a5.PNG)

**Comment by sreilly** [comment]
Do you have a non-default font size set in the preferences?

**Comment by Derekkent23** [comment]
See Screen shot
![Font Size](https://user-images.githubusercontent.com/59656614/116701904-5b915c00-a9c0-11eb-96e9-88bd41ccae4a.PNG)

**Comment by Derekkent23** [comment]
Following screen shot with default font size, results font to small to use in practise.
Don’t know if this is relevant but my computer is a Dell XP15 7590 Display resolution 3840x2160
![Default Font Size](https://user-images.githubusercontent.com/59656614/116775639-04d96000-aa5c-11eb-85cd-d98d6cc96a65.PNG)

**Comment by sreilly** [comment]
I think this is related to the selected font. I'm not seeing it with the default font, and some fonts have screwy metrics which makes it impossible to correctly measure the required width for some strings. Can you try using the default font or maybe some different options?

**Comment by Derekkent23** [comment]
2021.1(3068)
Setting to Defaults Fonts and Size does not help. See screen shots.
![Apperance Settings](https://user-images.githubusercontent.com/59656614/118979726-b0494680-b970-11eb-963e-965ca4685170.PNG)
![Networth Edit](https://user-images.githubusercontent.com/59656614/118979746-b5a69100-b970-11eb-9c8e-a064c4362edd.PNG)

**Comment by Derekkent23** [comment]
Sean, in case you are wondering changing theme to Default does not help.

**Comment by Derekkent23** [comment]
Another report of the same issue see https://infinitekind.tenderapp.com/discussions/problems/79080-selection-criteria-when-creating-graphs-and-reports-are-truncated

**Comment by Derekkent23** [comment]
his bug appear to have been fixed at some point as build 2023.3(5064) is OK.

**Comment by Derekkent23** [comment]
This bug appear to have been fixed at some point as build 2023.3(5064) is OK.
