### ISSUE TITLE
Mac - Since VAQua in Txn Register, the amount fields (display) corrupts when using cursor, delete etc

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#40]
Since VAQua, the transaction amount fields corrupt (the display) as soon as you use the backspace / delete key(s). Examples attached. You can ignore and keep typing or tab away and back to rectify. 
<img width="152" alt="Screenshot 2021-04-25 at 10 24 25" src="https://user-images.githubusercontent.com/22958485/115988230-8e96b280-a5b0-11eb-821f-8e64a3977ecf.png">
<img width="125" alt="Screenshot 2021-04-25 at 10 25 47" src="https://user-images.githubusercontent.com/22958485/115988252-a0785580-a5b0-11eb-843c-a15768bd66aa.png">

**Comment by sreilly** [comment]
This is fixed in the current preview

**Comment by yogi1967** [comment]
Confirmed. Fixed.
