### ISSUE TITLE
Reminders Column and Date issues.

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#44]
Tested on Windows 10 and Linux Feren OS
See video (unzip). Part of date is missing, adjusting the column width of the Date Field alone does not help, columns misalign. You then need to adjust the window size. Adjusting the window size alone does not help. The second part of the video shown that on adjusting column widths they misalign, snapping back if you adjust the window size.

[Reminders.zip](https://github.com/TheInfiniteKind/moneydance_open/files/6503262/Reminders.zip)

**Comment by sreilly** [comment]
re-posting the video inline
https://user-images.githubusercontent.com/470762/123456362-aa332f00-d5da-11eb-8be5-5d149fd5f367.mp4

**Comment by Derekkent23** [comment]
Hi Sean 2022(4040) only the first part of issues shown in the video has been fixed, Date. The rest of the issues in the video still needs fixing, column misalign after adjusting column width in the two subject windows

**Comment by Derekkent23** [comment]
The remaining problems in build 4040, have been fixed in build 4043.
