### ISSUE TITLE
Issue setting up a Security in a foreign currency. 

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#45]
Base Currency British Pounds. Setting up a new Security in US Dollars. A history of GBP\USD exchange rates exists.

First attempt, see video. Change of Security currency not remembered.

Second attempt, see video. The initial price for the security is 121.21 and I enter this as a Current Price.
When I click NEW the resulting Dated price is wrong and I have to edit it. At least after the edit when I open the Security history window again, the change of currency is remembered.

https://user-images.githubusercontent.com/59656614/118775067-6e3fd800-b87e-11eb-85ca-dd8f9a966ff1.mp4

**Comment by Derekkent23** [comment]
Second video (unzip)
[Setting up non-base Currency Security.zip](https://github.com/TheInfiniteKind/moneydance_open/files/6506847/Setting.up.non-base.Currency.Security.zip)

**Comment by sreilly** [comment]
I believe this is fixed for the next preview build. Nice catch!

**Comment by Derekkent23** [comment]
Issue is fixed in build 3069, Great!
