### ISSUE TITLE
Add filtering to Securities window

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#46]
Add INACTIVE tick box to securities selected under TOOLS - SECURITIES, to filter out unused securities from other selection lists. As with accounts under TOOLS – ACCOUNTS they could be greyed to denote tick box is ticked, but still editable.

**Comment by sreilly** [comment]
This list of securities should be filterable by used/unused/non-zero-balance/etc. There should also be a quick-search field to filter the list, and let's also show more information in the list. There's no reason this list of securities can't include the current price, last-updated date, exchange, base currency, and other information.

**Comment by dwg1957** [comment]
The ability to mark securities as inactive like we can accounts and categories is an often requested feature and is especially needed by those that have a lot of obsolete securities, that using the often suggested workarounds would create a lot of work.

**Comment by Derekkent23** [comment]
Inactive box added at some point to window under TOOLS - ACCOUNTS for each Security held in an Investment Account.

**Comment by Derekkent23** [comment]
Inactive box added at some point to window under TOOLS - ACCOUNTS for each Security held in an Investment Account.
