### ISSUE TITLE
Price of 0 being reported in information bar

### ISSUE THREAD

**Issue by dwg1957** [TheInfiniteKind/moneydance_open#5]
When downloading prices Q&ER is reporting the latest date but it is showing a price of 0.00 as an informational message. The correct price is being recorded in the history however. This issue has lead users in the past to believe that prices are not being downloaded.

**Comment by sreilly** [comment]
I believe this has been fixed, but can you confirm @dwg1957?

**Comment by dwg1957** [comment]
@sreilly I have performed some initial testing on Build 3068 with v1028 of Q&ER and so far the correct prices are being seen in the information bar.
