### ISSUE TITLE
Side Bar/Summary page issue when syncing.

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#51]
This is a long term issue when syncing computers. It can happen on primary or secondary computers. Occasionally on synced data sets when Moneydance is opened either totals in the Side Bar of Summary Page are way out. Closing and reopen Moneydance sorts things out. See screen shot for a example.
![MD 2021 1(6069) WRONG TOTAL BUG](https://user-images.githubusercontent.com/59656614/119129967-8014ad00-ba2f-11eb-9927-99a981718351.PNG)

**Comment by dtdseeker** [comment]
This is a problem I encounter fairly often. Closing and reopening Moneydance does not always fix the values. However, initiating an online download will sometimes correct this as well. It's problematic, and I have no idea why it happens other than having to do with syncing, as derekkent23 says.

**Comment by Derekkent23** [comment]
At some point this issue has been fixed.
