### ISSUE TITLE
Windows 10, Bug related to entering incorrect password. 

### ISSUE THREAD

**Issue by Derekkent23** [TheInfiniteKind/moneydance_open#55]
Tested on Moneydance 2021.1(3069) on Windows 10
See video 
Works OK on Linux Feren OS

https://user-images.githubusercontent.com/59656614/119266962-c7906a00-bbe4-11eb-8687-72e9f0dd68be.mp4

**Comment by yogi1967** [comment]
I was about to say that this does not occur on a Mac, but something strange randomly does occur - just not every time...

Sometimes I get a blank Please Enter Your Password box.... See SS.

<img width="260" alt="Screenshot 2021-06-02 at 10 21 39" src="https://user-images.githubusercontent.com/22958485/120455208-758dd800-c38c-11eb-8c0a-2de73ac29b31.png">

No errors in console.. First attempt, took 3 wrong tries. Second attempt took 5 wrong tries....

**Comment by yogi1967** [comment]
Derek is this fixed now? Sean fixed the issue I was seeing with a blank enter password box and it might be the same (ish) issue?

**Comment by sreilly** [comment]
This should be fixed. I'll close it, but feel free to reopen if you encounter this same issue again

**Comment by Derekkent23** [comment]
Agree, MD 4060 windows 10 & 11 issue fixed.
