### ISSUE TITLE
BUG - Transaction Filter report is not sorting / totalling by category correctly since 2021.1 build 3069

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#60]
The sort by category option is not working properly. It looks like it is not sorting before totalling; thus you get the category sort totalling whenever the next txn changes category.. Two scenarios seen thus far:

1/ One Account, several txns over several dates, crossing several categories.. The category total will reappear each time the category changes, but no prior sort.

https://infinitekind.tenderapp.com/discussions/problems/70547-transaction-filter-subtotal-by-category-quit-working-in-20211-3069

<img width="1436" alt="single account txns" src="https://user-images.githubusercontent.com/22958485/120453082-a1a85980-c38a-11eb-93ae-7e0409ab5e5c.png">

<img width="1429" alt="single account report" src="https://user-images.githubusercontent.com/22958485/120453085-a240f000-c38a-11eb-9bf7-61ec90c6892c.png">

2/ several accounts, using the same categories. Again, the category seen many times totalled in the wrong places..

https://infinitekind.tenderapp.com/discussions/problems/70615-version-20211-3069-transaction-filter-report-does-not-subtotal-correctly-when-category-selected

<img width="1434" alt="multi-acct test txns1" src="https://user-images.githubusercontent.com/22958485/120453071-9fde9600-c38a-11eb-8992-1115f57f9de0.png">

<img width="1427" alt="multi-acct test txns2" src="https://user-images.githubusercontent.com/22958485/120453075-a0772c80-c38a-11eb-98fa-1390c8aaaf48.png">

<img width="1438" alt="multi-acct test report" src="https://user-images.githubusercontent.com/22958485/120453078-a10fc300-c38a-11eb-9e27-003e294fff64.png">

**Comment by sreilly** [comment]
This is fixed. There are other side-effect issues, but this one's fixed
