### ISSUE TITLE
[BUG]  Clicking on the Category header in the register doesn't sort in alphabetical order

### ISSUE THREAD

**Issue by m4ddym3** [TheInfiniteKind/moneydance_open#69]
I've clicked on "Category" header to sort, see the arrow next to Category showing that it (thinks) it's sorting by category, but see that it's actually sorted by Date, not by Category.

![image](https://user-images.githubusercontent.com/60185712/150375551-7ff75d7c-4a78-4428-8d1b-f3da66ee54b2.png)

Moneydance 2022.3 (4063) on Mac and Windows.

**Comment by sreilly** [comment]
Thanks for catching this! It's fixed for the next preview
