### ISSUE TITLE
Security Lot Matching Error

### ISSUE THREAD

**Issue by sreilly** [TheInfiniteKind/moneydance_open#70]
Reported by reznor in a [slack thread](https://infinitekind-public.slack.com/archives/C28AV3615/p1646778628687949):

> I've found a problem with the code that displays lot matching for a security. I thought I had some corrupted data but it appears to be a program issue.
> I can reproduce with this:
	• Create a new security in an investment account
	• Purchase (BuyXfr) 100 shares on 1/1/22 and then 50 shares on 1/5/22
	• Sell 50 shares on 1/10/22 matched to the 1/5/22 purchase
	• Stock splits 2/1 on 1/15/22
	• Sell 200 (split adjusted) shares on 1/20/22 matched the the 1/1/22 purchase
> When selecting the 1/10/22 date in the lot matching window it should show two lots:
	1/1/22, 100 shares available, 0 allocated
	1/5/22, 50 shares available, 50 allocated
> But instead the 1/10/22 date shows:
	1/1/22, -100 shares available, 0 allocated
	1/5/22, 50 shares available, 50 allocated
> While the 1/20/22 date shows:
	1/1/22, 200 shares available, 200 allocated
	1/5/22, 0 shares available, 0 allocated
> Whatever is calculating that -100 entry is incorrect.

dummy security used to test:
![image](https://user-images.githubusercontent.com/470762/158358133-a3446abb-78b2-434f-a121-c1b66ddd63e6.png)

the lots:
![image](https://user-images.githubusercontent.com/470762/158358177-e2b93f12-05da-4364-89df-753995b8e88e.png)
![image](https://user-images.githubusercontent.com/470762/158358208-cf17b870-11e2-4ce3-a41f-34d171acc32f.png)

and a file that shows the issue:
[Personal Finances-20220310-1013.moneydancearchive.zip](https://github.com/TheInfiniteKind/moneydance_open/files/8252331/Personal.Finances-20220310-1013.moneydancearchive.zip)

**Comment by yogi1967** [comment]
Ok. This is an issue. I almost thought it wasn't as the symptom doesn't actually appear until you match the 200/100 (using this example). Ie - before you match, it all visually looks ok. This match crosses a split date. TBH - I'm puzzled that more people haven't complained about this...

Anyway, I'm investigating...

FYI - the cost basis code has been recently rewritten (unifying code for both lots and average) and should be included in the next preview. I actually think this issue could be cosmetic and that the matched data is correct. I hope the cost basis and gains, in the next preview, actually deal with this properly. 

Anyway, I'll see if I can pinpoint the actual error in the lot window....

**Comment by yogi1967** [comment]
Confirmed this is cosmetic. 

I have provided and tested a code fix for this issue. It's with IK to review. 

In your scenario CapitalGains was correct. 

As mentioned, there are fixes coming anyway with a new cost basis / capital gains calculations that should fix other issues you allude to.

**Comment by yogi1967** [comment]
FYI. This should be in the latest Alpha MD2024(5101)
