### ISSUE TITLE
Show the total value of selected rows

### ISSUE THREAD

**Issue by lordpixel23** [TheInfiniteKind/moneydance_open#84]
When I select rows in a spreadsheet, it shows the Total, Average and Count of the rows selected.

I can't even tell you how many times I've wished Moneydance would do the same. I filter a view in Moneydance, select some rows and I have no idea what they add up to.

**Comment by yogi1967** [comment]
Install toolbox extension. In a register, highlight rows and then click extensions, toolbox: total selected txns. 

Note: recent MD builds do total selected rows on some account types (bottom right).

**Comment by lordpixel23** [comment]
Thanks. More recent than 2022.4 I take it?

**Comment by yogi1967** [comment]
Nope. The inbuilt total works on 2022.4. (Not in investment registers, only in bank registers). 

The extension works on all recent builds.

**Comment by sreilly** [comment]
Yep, this has been there for a while. Is there any place that it's not already that you'd like to see @lordpixel23?

<img width="376" alt="image" src="https://user-images.githubusercontent.com/470762/178145473-92a9ada4-f99c-43a4-81b1-1463669a84ba.png">

**Comment by lordpixel23** [comment]
As Yogi says above, it doesn't work in investment registers.

**Comment by yogi1967** [comment]
@lordpixel23 - this functionality (enhanced selection values, including for investment accounts) has now been built and should appear in the next MD release....

**Comment by lordpixel23** [comment]
Thank you. Great news indeed.
