### ISSUE TITLE
LEAK-REF: 15.0 - VAQua: changeListeners (AWAITING JAR IMPLEMENTATION)

### ISSUE THREAD

**Issue by yogi1967** [TheInfiniteKind/moneydance_open#99]
... holding on to references to closed datasets. VAqua developer confirmed bug. New VAqua build tested and confirmed ok. Just needs including into MD release. Refer: https://github.com/violetlib/vaqua/issues/35

**Comment by sreilly** [comment]
This doesn't seem vaqua related.  I think I've fixed this by clearing the key bindings map:
<img width="420" alt="image" src="https://github.com/TheInfiniteKind/moneydance_open/assets/470762/698ee010-7a93-4532-a2b4-0814abb2d570">

**Comment by yogi1967** [comment]
It's 100% VAqua and this was confirmed by cbfiddle. He fixed it. I proved the issue only existed in VAqua and that it was resolved afterwards. Remember? We have the new VAqua build jar... just needs implementing.

**Comment by yogi1967** [comment]
Fixed in 5050 - includes VAqua12
